### ISSUE TITLE
Failed to start app.outgoing with AttributeError exception from asyncio

### ISSUE THREAD

**Issue by dev-digital** [uktrade/activity-stream#221]
**Description**

As per the readme, local env was setup with python **3.6** as runtime. On running the outgoing app, AttributeError exception was received with below error

_module asyncio has no attribute 'get_running_loop'_

However above attribute was added to asyncio from [3.7](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop)

Hence docs must be updated with required runtime as **3.7 or later** 

**Expected behaviour **
Application to run w/o any errors

**Comment by michalc** [comment]
We're now on Python 3.11
